### ISSUE TITLE
RemoveOld -> Date enhancement

### ISSUE THREAD

**Issue by HieiOne** [alex13lopez/gcloud-backup#9]
https://github.com/alex13lopez/gcloud-backups/blob/48fc854e3b6e3c742f69aba69d746501bfc8a5da/GcloudBackup.ps1#L195

This function is hard to digest, we should do it simpler like this:

We get the today date and we substract it from the fileDate (in days) if its bigger than the Days to keep backup it should be deleted (also if its 0 it should be ignored)

**Comment by alex13lopez** [comment]
Yeah you're right, it's way simpler that way. Idk why I did it so complicated, it does work though but I get it might be difficult to read.
